[package]
name = "my_arr_math"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my_fractions = {path = "{...}/my_fractions",optional=true}

[features]
fractions = ["dep:my_fractions"]
